version: '3'

services:
  web:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
